SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, D.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM APPOINTMENT AS A
INNER JOIN DOCTOR AS D
INNER JOIN PATIENT AS P
ON D.DR_ID = A.MDDR_ID
AND P.PT_NO = A.PT_NO
WHERE A.APNT_YMD LIKE '2022-04-13%'
AND A.APNT_CNCL_YN = 'N'
AND D.MCDP_CD = 'CS'
ORDER BY A.APNT_YMD;