SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES 
FROM USED_GOODS_USER AS U 
INNER JOIN USED_GOODS_BOARD AS B ON B.WRITER_ID = U.USER_ID
WHERE B.STATUS LIKE 'DONE'
GROUP BY U.USER_ID 
HAVING SUM(B.PRICE) >= 700000
ORDER BY TOTAL_SALES;
