SELECT FACTORY_ID, FACTORY_NAME, ADDRESS FROM FOOD_FACTORY WHERE ADDRESS LIKE '강원도%' 
ORDER BY FACTORY_ID;SELECT WAREHOUSE_ID,WAREHOUSE_NAME,ADDRESS,
IF(ISNULL(FREEZER_YN),'N',FREEZER_YN) AS FREEZER_YN 
FROM FOOD_WAREHOUSE AS F WHERE F.WAREHOUSE_NAME LIKE '%경기%'; 