-- 1번 GROUP BY
SELECT CART_ID FROM CART_PRODUCTS 
WHERE NAME IN ('Milk','Yogurt')
GROUP BY CART_ID
HAVING COUNT(DISTINCT NAME) >= 2
ORDER BY ID;

-- 2번 GROUP_CONCAT
SELECT CART_ID
FROM (
    SELECT CART_ID, GROUP_CONCAT(NAME) AS NAMES
    FROM CART_PRODUCTS
    GROUP BY CART_ID
) TMP

WHERE NAMES LIKE '%Milk%' 
    AND NAMES LIKE '%Yogurt%' 

-- 3번 JOIN

WITH M AS (
SELECT DISTINCT CART_ID, NAME FROM CART_PRODUCTS
WHERE NAME = 'Milk'),
Y AS (
SELECT DISTINCT CART_ID, NAME FROM CART_PRODUCTS
WHERE NAME = 'Yogurt')

SELECT Y.CART_ID
FROM Y
INNER JOIN M
ON Y.CART_ID = M.CART_ID;