SELECT CONCAT('/home/grep/src/',F.BOARD_ID,'/',F.FILE_ID, F.FILE_NAME, F.FILE_EXT) AS FILE_PATH 
FROM USED_GOODS_FILE AS F INNER JOIN USED_GOODS_BOARD AS B
ON F.BOARD_ID = B.BOARD_ID
WHERE B.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY F.FILE_ID DESC;