SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * S.SALES) AS TOTAL_SALES FROM BOOK AS B
INNER JOIN AUTHOR AS A
INNER JOIN BOOK_SALES AS S
ON B.AUTHOR_ID = A.AUTHOR_ID AND B.BOOK_ID = S.BOOK_ID
WHERE S.SALES_DATE LIKE '2022-01%'
GROUP BY B.CATEGORY,A.AUTHOR_ID
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC;